"""empty message

Revision ID: 0b8cbaf01c2f
Revises: 93b852efcc9b
Create Date: 2024-04-27 16:49:36.259767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8cbaf01c2f'
down_revision = '93b852efcc9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_appointment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'medical_appointment', ['medical_appointment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('medical_appointment_id')

    # ### end Alembic commands ###
