"""empty message

Revision ID: 4826e026cc8c
Revises: 8cf5af61601d
Create Date: 2024-04-12 18:35:32.659113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4826e026cc8c'
down_revision = '8cf5af61601d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('identification',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('social_security',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('alergic',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('medicated',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('medicated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('alergic',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('social_security',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('identification',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
