"""empty message

Revision ID: 806ec700f9d6
Revises: 0b8cbaf01c2f
Create Date: 2024-04-27 16:58:10.968816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806ec700f9d6'
down_revision = '0b8cbaf01c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_constraint('meetings_medical_appointment_id_fkey', type_='foreignkey')
        batch_op.drop_column('medical_appointment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_appointment_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('meetings_medical_appointment_id_fkey', 'medical_appointment', ['medical_appointment_id'], ['id'])

    # ### end Alembic commands ###
