"""empty message

Revision ID: 93b852efcc9b
Revises: a8005fbd2075
Create Date: 2024-04-27 16:30:02.385038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b852efcc9b'
down_revision = 'a8005fbd2075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'meetings', ['meeting_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('meeting_id')

    # ### end Alembic commands ###
